### ISSUE TITLE
Corrigir erro de CORS

### ISSUE THREAD

**Issue by Wictorgirardi** [fga-eps-mds/2022-1-EuPescador-Doc#18]
### Descrição:
Não está sendo possível realizar requisições no frontend devido a um erro de CORS.

### Tarefas
Seção para tarefas (tasks) para issues mais complexas ou sub-tarefas. 
- [ ] Bugfix.

**Comment by pedro-rodiguero** [comment]
Estou resolvendo agora, por favor me coloquem como assignee.
Valeu!

**Comment by Wictorgirardi** [comment]
O @pedro-rodiguero Realizou essa tarefa.
